package chenbo.work.crm.mapper.user;

import chenbo.work.crm.entity.user.RolePermissionRelation;
import java.util.List;

public interface RolePermissionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_permission_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_permission_relation
     *
     * @mbg.generated
     */
    int insert(RolePermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_permission_relation
     *
     * @mbg.generated
     */
    RolePermissionRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_permission_relation
     *
     * @mbg.generated
     */
    List<RolePermissionRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_permission_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RolePermissionRelation record);
}