package chenbo.work.crm.entity.user;

import java.util.Date;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permission.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permission.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permission.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permission.moduleUrl
     *
     * @mbg.generated
     */
    private String moduleurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permission.orderId
     *
     * @mbg.generated
     */
    private Long orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permission.tempstamp
     *
     * @mbg.generated
     */
    private Date tempstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permission.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permission.id
     *
     * @return the value of tbl_permission.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permission.id
     *
     * @param id the value for tbl_permission.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permission.pid
     *
     * @return the value of tbl_permission.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permission.pid
     *
     * @param pid the value for tbl_permission.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permission.name
     *
     * @return the value of tbl_permission.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permission.name
     *
     * @param name the value for tbl_permission.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permission.moduleUrl
     *
     * @return the value of tbl_permission.moduleUrl
     *
     * @mbg.generated
     */
    public String getModuleurl() {
        return moduleurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permission.moduleUrl
     *
     * @param moduleurl the value for tbl_permission.moduleUrl
     *
     * @mbg.generated
     */
    public void setModuleurl(String moduleurl) {
        this.moduleurl = moduleurl == null ? null : moduleurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permission.orderId
     *
     * @return the value of tbl_permission.orderId
     *
     * @mbg.generated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permission.orderId
     *
     * @param orderid the value for tbl_permission.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permission.tempstamp
     *
     * @return the value of tbl_permission.tempstamp
     *
     * @mbg.generated
     */
    public Date getTempstamp() {
        return tempstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permission.tempstamp
     *
     * @param tempstamp the value for tbl_permission.tempstamp
     *
     * @mbg.generated
     */
    public void setTempstamp(Date tempstamp) {
        this.tempstamp = tempstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permission.status
     *
     * @return the value of tbl_permission.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permission.status
     *
     * @param status the value for tbl_permission.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}