package chenbo.work.crm.entity.user;

import java.util.Date;

public class RolePermissionRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role_permission_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role_permission_relation.roleId
     *
     * @mbg.generated
     */
    private Long roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role_permission_relation.permissionId
     *
     * @mbg.generated
     */
    private Long permissionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role_permission_relation.orderId
     *
     * @mbg.generated
     */
    private Long orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role_permission_relation.timestamp
     *
     * @mbg.generated
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role_permission_relation.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role_permission_relation.id
     *
     * @return the value of tbl_role_permission_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role_permission_relation.id
     *
     * @param id the value for tbl_role_permission_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role_permission_relation.roleId
     *
     * @return the value of tbl_role_permission_relation.roleId
     *
     * @mbg.generated
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role_permission_relation.roleId
     *
     * @param roleid the value for tbl_role_permission_relation.roleId
     *
     * @mbg.generated
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role_permission_relation.permissionId
     *
     * @return the value of tbl_role_permission_relation.permissionId
     *
     * @mbg.generated
     */
    public Long getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role_permission_relation.permissionId
     *
     * @param permissionid the value for tbl_role_permission_relation.permissionId
     *
     * @mbg.generated
     */
    public void setPermissionid(Long permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role_permission_relation.orderId
     *
     * @return the value of tbl_role_permission_relation.orderId
     *
     * @mbg.generated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role_permission_relation.orderId
     *
     * @param orderid the value for tbl_role_permission_relation.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role_permission_relation.timestamp
     *
     * @return the value of tbl_role_permission_relation.timestamp
     *
     * @mbg.generated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role_permission_relation.timestamp
     *
     * @param timestamp the value for tbl_role_permission_relation.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role_permission_relation.status
     *
     * @return the value of tbl_role_permission_relation.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role_permission_relation.status
     *
     * @param status the value for tbl_role_permission_relation.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}