package chenbo.work.crm.dao.user.mapper;

import chenbo.work.crm.dao.user.entity.RolePermissionRelation;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

import java.util.List;

public interface RolePermissionRelationMapper extends BaseMapper<RolePermissionRelation> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_permission_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_permission_relation
     *
     * @mbg.generated
     */
    int insert(RolePermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_permission_relation
     *
     * @mbg.generated
     */
    RolePermissionRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_permission_relation
     *
     * @mbg.generated
     */
    List<RolePermissionRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_permission_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RolePermissionRelation record);
}