package chenbo.work.crm.dao.user.mapper;

import chenbo.work.crm.dao.user.entity.UserRoleRelation;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

import java.util.List;

public interface UserRoleRelationMapper extends BaseMapper<UserRoleRelation> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role_relation
     *
     * @mbg.generated
     */
    int insert(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role_relation
     *
     * @mbg.generated
     */
    UserRoleRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role_relation
     *
     * @mbg.generated
     */
    List<UserRoleRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRoleRelation record);
}