package chenbo.work.crm.dao.user.entity;

import java.util.Date;

public class UserRoleRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_role_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_role_relation.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_role_relation.roleId
     *
     * @mbg.generated
     */
    private Long roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_role_relation.orderId
     *
     * @mbg.generated
     */
    private Long orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_role_relation.timestapm
     *
     * @mbg.generated
     */
    private Date timestapm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_role_relation.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_role_relation.id
     *
     * @return the value of tbl_user_role_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_role_relation.id
     *
     * @param id the value for tbl_user_role_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_role_relation.userId
     *
     * @return the value of tbl_user_role_relation.userId
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_role_relation.userId
     *
     * @param userid the value for tbl_user_role_relation.userId
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_role_relation.roleId
     *
     * @return the value of tbl_user_role_relation.roleId
     *
     * @mbg.generated
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_role_relation.roleId
     *
     * @param roleid the value for tbl_user_role_relation.roleId
     *
     * @mbg.generated
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_role_relation.orderId
     *
     * @return the value of tbl_user_role_relation.orderId
     *
     * @mbg.generated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_role_relation.orderId
     *
     * @param orderid the value for tbl_user_role_relation.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_role_relation.timestapm
     *
     * @return the value of tbl_user_role_relation.timestapm
     *
     * @mbg.generated
     */
    public Date getTimestapm() {
        return timestapm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_role_relation.timestapm
     *
     * @param timestapm the value for tbl_user_role_relation.timestapm
     *
     * @mbg.generated
     */
    public void setTimestapm(Date timestapm) {
        this.timestapm = timestapm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_role_relation.status
     *
     * @return the value of tbl_user_role_relation.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_role_relation.status
     *
     * @param status the value for tbl_user_role_relation.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}